name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on: codebuild-git_hub_final_final-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World!"
      - run: hostname
